const imageGridCards = [
{
id:"1",
imageId:"PC_Mweb/Pizza.png",
action:{link:"#",text:"Pizza",type:"DEEPLINK"}
},
{
id:"2",
imageId:"PC_Mweb/Burger.png",
action:{link:"#",text:"Burger",type:"DEEPLINK"}
},
{
id:"3",
imageId:"PC_Mweb/Biryani.png",
action:{link:"#",text:"Biryani",type:"DEEPLINK"}
},
{
id:"4",
imageId:"PC_Mweb/Rolls.png",
action:{link:"#",text:"Rolls",type:"DEEPLINK"}
},
{
id:"5",
imageId:"PC_Mweb/Cakes.png",
action:{link:"#",text:"Cake",type:"DEEPLINK"}
},
{
id:"6",
imageId:"PC_Mweb/Momos.png",
action:{link:"#",text:"Momo",type:"DEEPLINK"}
},
{
id:"7",
imageId:"PC_Mweb/Noodles.png",
action:{link:"#",text:"Noodles",type:"DEEPLINK"}
},
{
id:"8",
imageId:"PC_Mweb/Dosa.png",
action:{link:"#",text:"Dosa",type:"DEEPLINK"}
},
{
id:"9",
imageId:"PC_Mweb/Idli.png",
action:{link:"#",text:"Idli",type:"DEEPLINK"}
},
{
id:"10",
imageId:"PC_Mweb/Paratha.png",
action:{link:"#",text:"Paratha",type:"DEEPLINK"}
},
{
id:"11",
imageId:"PC_Mweb/Sandwich.png",
action:{link:"#",text:"Sandwich",type:"DEEPLINK"}
}
];

export default imageGridCards;